name: 'Flutter Pubspec Updater'
description: 'Update pubspec.yaml based on results from $ flutter pub outdated'
author: 'Kuan Yi Ng'
inputs:
  pathToPubspecFile:
    required: true
    description: 'relative path to pubspec.yaml file from root directory'
    default: './pubspec.yaml'
outputs:
  pullRequestRequired:
    description: 'a boolean value deciding if a new pull request should be made or not (using another GitHub Action)'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'package'
  color: 'blue'
