name: 'Update Flutter Packages'
description: 'Update pubspec.yaml based on results from $ flutter pub outdated'
author: 'Kuan Yi Ng'
inputs:
  pathToPubspecFile:
    required: true
    description: 'relative path to pubspec.yaml file from root directory'
    default: './pubspec.yaml'
runs:
  using: 'node12'
  main: 'dist/index.js'
