name: 'build-test'

on:
  pull_request:

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # or: 'beta' or 'dev'

      - name: Update pubspec.yaml
        uses: ./

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: 'update pubspec.yaml based on `$ flutter pub outdated`'
          branch: flutter-pub-outdated
          base: main
          delete-branch: true
          title: 'Update Pubspec.yaml'
          body: 'update pubspec.yaml based on `$ flutter pub outdated`'
          labels: 'dependencies'
